apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-ui
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-ui
  template:
    metadata:
      labels:
        app: redis-ui
    spec:
      containers:
      - name: redis-ui
        image: rediscommander/redis-commander:latest # אימג' מודרני ותקין
        env:
        - name: REDIS_HOSTS
          value: "local:redis-service:6379" # מתחבר לשירות שיצרת קודם
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: devops
spec:
  type: ClusterIP
  selector:
    app: redis-ui
  ports:
    - port: 80
      targetPort: 8081